export const siteConfig = {
  name: "LietuCoach",
  tagline: "Learn Lithuanian for everyday situations.",
  description: "The offline-first Lithuanian app for beginners. Practice real conversations, learn practical phrases, and build confidence - no internet required.",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://lietucoach.app",
  links: {
    twitter: "https://twitter.com/lietucoach",
    github: "https://github.com/lietucoach",
    supportEmail: "hello@dhossain.com",
    playStore: "https://play.google.com/store/apps/details?id=app.lietucoach.lietucoach",
  },
  author: {
    name: "LietuCoach Team",
    url: "https://lietucoach.app",
  },
  keywords: [
    "learn Lithuanian",
    "Lithuanian language app",
    "offline Lithuanian learning",
    "Lithuanian phrases",
    "speak Lithuanian",
    "Lithuanian conversation practice",
    "Lithuanian for beginners",
    "Vilnius guide",
    "Lithuanian grammar basics",
    "Lithuanian travel phrases",
  ],
  version: "1.0.0",
  lastUpdated: new Date().toISOString().split("T")[0],
};